name: 🐞 Bug Report
description: Report something that isn't working as expected in BOTB
title: "[BUG] <brief description>"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        👋 Thanks for reporting a bug in BOTB!
        Please fill out all fields so we can fix it quickly.

  - type: input
    id: version
    attributes:
      label: BOTB Version
      description: What version of BOTB were you using?
      placeholder: e.g. 1.0.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS were you running BOTB on?
      placeholder: e.g. Windows 11 Pro, Kali Linux Rolling

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Be as clear as possible so we can recreate the issue.
      placeholder: |
        1. Ran botb.py on folder X
        2. Expected it to rename files
        3. Got error in debug.txt
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: e.g. The folders should be renamed and extraction should begin...

  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
      placeholder: e.g. Script crashed with traceback...

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant `debug.txt` entries or screenshots (if any)
